language: objective-c

env:
  global:
  - AWS_DEFAULT_REGION=us-standard
  - AWS_ACCESS_KEY_ID=AKIAI2ERWDHLW3W24X3A
  - secure: "WSqA/RbX5O02CzjX2exYVNfIzgOotMYY+R8aooDTLVL0YePshZ/jj9SPELjCx6alp4xcUYEEPlqrdLznBN2yA/Lxjyjyd0DIHMubF4eiEgnwp9DO/29iLaikScIGKwvVq3yS0ThL4qPzrwQC91cG1EotY2SECFf6oWkmzcbT86g="

script:
  - python setup.py py2app fix bundle
  - aws s3 cp dist/*dmg s3://mac.glueviz.org/

before_install:
  # Avoid conflict with system-installed versions of various libraries by
  # removing all homebrew packages, then re-installing wget.
  - brew remove --force $(brew list)
  - brew install wget

install:
  - wget https://repo.continuum.io/miniconda/Miniconda-3.10.1-MacOSX-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/Users/travis/miniconda/bin:$PATH
  - conda update --quiet --yes conda
  - conda install --quiet --yes pip nomkl numpy scipy matplotlib=1.4.3=np19py27_2 pandas astropy pygments pyzmq ipython=3 scikit-image h5py py requests pytz mock requests pytest pyside
  - conda remove --force setuptools
  - pip install setuptools
  - pip install macholib==1.5.1 modulegraph==0.11 py2app==0.7
  - pip install pyavm plotly awscli==1.3.16 astrodendro
  - git clone git://github.com/glue-viz/glue.git
  - cd glue
  - git checkout $TRAVIS_BRANCH
  - python setup.py install
  - cd ../
  - conda list
